### ISSUE TITLE
regarding image

### ISSUE THREAD

**Issue by Rohitupadhyay1993** [gaiterjones/magento-htmlinvoice#9]
unable to print product image on pdf invoice

**Comment by gaiterjones** [comment]
This module creates an html invoice, not a pdf invoice.

**Comment by Rohitupadhyay1993** [comment]
i want to add product images on html invoice is it possible.

**Comment by gaiterjones** [comment]
You need to set "Show product image on invoice" to YES in Admin -> My Extensions -> HTML Invoice

**Comment by Rohitupadhyay1993** [comment]
thanx a lot greate.....
